<a href="https://colab.research.google.com/github/AyushSinha2210/Machine_Learning/blob/main/Preparing_Data_For_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
import time

print("Loading data file now, this could take a while depending on file size")
start=time.time()
df=pd.read_csv('/content/Hotel_Reviews.csv')
end=time.time()
print("Loading took"+str(round(end-start,2))+"seconds")

Loading data file now, this could take a while depending on file size
Loading took4.26seconds

In [3]:
df.describe()

,Additional_Number_of_Scoring,Average_Score,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,lat,lng
count,515738.000000,515738.000000,515738.000000,515738.000000,515738.000000,515738.000000,515738.000000,512470.000000,512470.000000
mean,498.081836,8.397487,18.539450,2743.743944,17.776458,7.166001,8.395077,49.442439,2.823803
std,500.538467,0.548048,29.690831,2317.464868,21.804185,11.040228,1.637856,3.466325,4.579425
min,1.000000,5.200000,0.000000,43.000000,0.000000,1.000000,2.500000,41.328376,-0.369758
25%,169.000000,8.100000,2.000000,1161.000000,5.000000,1.000000,7.500000,48.214662,-0.143372
50%,341.000000,8.400000,9.000000,2134.000000,11.000000,3.000000,8.800000,51.499981,0.010607
75%,660.000000,8.800000,23.000000,3613.000000,22.000000,8.000000,9.600000,51.516288,4.834443
max,2682.000000,9.800000,408.000000,16670.000000,395.000000,355.000000,10.000000,52.400181,16.429233

In [4]:
print("The shape of the data (rows, cols) is " + str(df.shape))

The shape of the data (rows, cols) is (515738, 17)

In [5]:
nat_freq=df["Reviewer_Nationality"].value_counts()
print("There are "+str(nat_freq.size)+" different nationalities")
print(nat_freq)

There are 227 different nationalities
Reviewer_Nationality
United Kingdom               245246
United States of America      35437
Australia                     21686
Ireland                       14827
United Arab Emirates          10235
                              ...
Cape Verde                        1
Northern Mariana Islands          1
Tuvalu                            1
Guinea                            1
Palau                             1
Name: count, Length: 227, dtype: int64

In [6]:
print("The highest freq reviewer nationality is "+str(nat_freq.index[0]).strip()+" with "+str(nat_freq[0])+" reviews.")
print("The next top 10 are: ")
print(nat_freq[1:11].to_string())

The highest freq reviewer nationality is United Kingdom with 245246 reviews.
The next top 10 are:
Reviewer_Nationality
United States of America     35437
Australia                    21686
Ireland                      14827
United Arab Emirates         10235
Saudi Arabia                  8951
Netherlands                   8772
Switzerland                   8678
Germany                       7941
Canada                        7894
France                        7296

/tmp/ipython-input-2939006229.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("The highest freq reviewer nationality is "+str(nat_freq.index[0]).strip()+" with "+str(nat_freq[0])+" reviews.")

In [7]:
for i in nat_freq[:10].index:
  nat_df=df[df["Reviewer_Nationality"]==i]
  freq=nat_df["Hotel_Name"].value_counts()
  print("The most reviewed hotel is "+str(i).strip()+" was "+str(freq.index[0])+" reviews.")

The most reviewed hotel is United Kingdom was Britannia International Hotel Canary Wharf reviews.
The most reviewed hotel is United States of America was Hotel Esther a reviews.
The most reviewed hotel is Australia was Park Plaza Westminster Bridge London reviews.
The most reviewed hotel is Ireland was Copthorne Tara Hotel London Kensington reviews.
The most reviewed hotel is United Arab Emirates was Millennium Hotel London Knightsbridge reviews.
The most reviewed hotel is Saudi Arabia was The Cumberland A Guoman Hotel reviews.
The most reviewed hotel is Netherlands was Jaz Amsterdam reviews.
The most reviewed hotel is Switzerland was Hotel Da Vinci reviews.
The most reviewed hotel is Germany was Hotel Da Vinci reviews.
The most reviewed hotel is Canada was St James Court A Taj Hotel London reviews.

In [8]:
# First create a new dataframe based on the old one, removing the uneeded columns
hotel_freq_df = df.drop(["Hotel_Address", "Additional_Number_of_Scoring", "Review_Date", "Average_Score", "Reviewer_Nationality", "Negative_Review", "Review_Total_Negative_Word_Counts", "Positive_Review", "Review_Total_Positive_Word_Counts", "Total_Number_of_Reviews_Reviewer_Has_Given", "Reviewer_Score", "Tags", "days_since_review", "lat", "lng"], axis = 1)

# Group the rows by Hotel_Name, count them and put the result in a new column Total_Reviews_Found
hotel_freq_df['Total_Reviews_Found'] = hotel_freq_df.groupby('Hotel_Name').transform('count')

# Get rid of all the duplicated rows
hotel_freq_df = hotel_freq_df.drop_duplicates(subset = ["Hotel_Name"])
display(hotel_freq_df)

,Hotel_Name,Total_Number_of_Reviews,Total_Reviews_Found
0,Hotel Arena,1403,405
405,K K Hotel George,1831,566
971,Apex Temple Court Hotel,2619,1037
2008,The Park Grand London Paddington,4380,1770
3778,Monhotel Lounge SPA,171,35
...,...,...,...
511962,Suite Hotel 900 m zur Oper,3461,439
512401,Hotel Amadeus,717,144
512545,The Berkeley,232,100
512645,Holiday Inn London Kensington,5945,2768
515413,Atlantis Hotel Vienna,2823,325

In [9]:
def get_difference_review_avg(row):
  return row["Average_Score"]-row["Cal_Average_Scores"]

df['Cal_Average_Scores']=round(df.groupby('Hotel_Name').Reviewer_Score.transform('mean'),1)
df['Average_Score_Difference']=df.apply(get_difference_review_avg, axis=1)
review_scores_df=df.drop_duplicates(subset=["Hotel_Name"])
review_scores_df=review_scores_df.sort_values(by=["Average_Score_Difference"])
display(review_scores_df[["Average_Score_Difference","Average_Score","Cal_Average_Scores","Hotel_Name"]])

,Average_Score_Difference,Average_Score,Cal_Average_Scores,Hotel_Name
495945,-0.8,7.7,8.5,Best Western Hotel Astoria
111027,-0.7,8.8,9.5,Hotel Stendhal Place Vend me Paris MGallery by...
43688,-0.7,7.5,8.2,Mercure Paris Porte d Orleans
178253,-0.7,7.9,8.6,Renaissance Paris Vendome Hotel
71274,-0.5,8.9,9.4,Drawing Hotel
...,...,...,...,...
201776,0.7,7.5,6.8,Mercure Paris Op ra Faubourg Montmartre
22189,0.8,7.1,6.3,Holiday Inn Paris Montparnasse Pasteur
250308,0.9,8.6,7.7,MARQUIS Faubourg St Honor Relais Ch teaux
68936,0.9,6.8,5.9,Villa Eugenie
3813,1.3,7.2,5.9,Kube Hotel Ice Bar

In [10]:
# without lambdas (using a mixture of notations to show you can use both)
start = time.time()
no_negative_reviews = sum(df.Negative_Review == "No Negative")
print("Number of No Negative reviews: " + str(no_negative_reviews))

no_positive_reviews = sum(df["Positive_Review"] == "No Positive")
print("Number of No Positive reviews: " + str(no_positive_reviews))

both_no_reviews = sum((df.Negative_Review == "No Negative") & (df.Positive_Review == "No Positive"))
print("Number of both No Negative and No Positive reviews: " + str(both_no_reviews))

end = time.time()
print("Sum took " + str(round(end - start, 2)) + " seconds")

Number of No Negative reviews: 127890
Number of No Positive reviews: 35946
Number of both No Negative and No Positive reviews: 127
Sum took 0.32 seconds

In [11]:
def replace_address(row):
  if "Netherlands" in row["Hotel_Address"]:
    return "Netherlands"
  elif "United Kingdom" in row["Hotel_Address"]:
    return "United Kingdom"
  elif "Barcelona" in row["Hotel_Address"]:
    return "Spain"
  elif "Milan" in row["Hotel_Address"]:
    return "Milan,Italy"
  elif "Vienna" in row["Hotel_Address"]:
    return "Vienna,Austria"
  elif "France" in row["Hotel_Address"]:
    return "paris,France"

df["Hotel_Address"] = df.apply(replace_address, axis = 1)

print(df["Hotel_Address"].value_counts())

Hotel_Address
United Kingdom    262301
Spain              60149
paris,France       59928
Netherlands        57214
Vienna,Austria     38939
Milan,Italy        37207
Name: count, dtype: int64

In [12]:
display(df.groupby("Hotel_Address").agg({"Hotel_Name": "nunique"}))

                Hotel_Name
Hotel_Address
Milan,Italy            162
Netherlands            105
Spain                  211
United Kingdom         400
Vienna,Austria         158
paris,France           458

In [13]:
df['Total_Number_of_Reviews'] = df.groupby('Hotel_Name')['Hotel_Name'].transform('size')
df['Average_Score'] = round(df.groupby('Hotel_Name')['Reviewer_Score'].transform('mean'),1)

In [14]:
df.drop(["Additional_Number_of_Scoring"],axis=1,inplace=True)

In [15]:
# Remove opening and closing brackets
df.Tags = df.Tags.str.strip("[']")
# remove all quotes too
df.Tags = df.Tags.str.replace(" ', '", ",", regex = False)

In [16]:
df["Leisure_trip"] = df.Tags.apply(lambda tag: 1 if "Leisure trip" in tag else 0)
df["Couple"] = df.Tags.apply(lambda tag: 1 if "Couple" in tag else 0)
df["Solo_traveler"] = df.Tags.apply(lambda tag: 1 if "Solo traveler" in tag else 0)
df["Business_trip"] = df.Tags.apply(lambda tag: 1 if "Business trip" in tag else 0)
df["Group"] = df.Tags.apply(lambda tag: 1 if "Group" in tag or "Travelers with friends" in tag else 0)
df["Family_with_young_children"] = df.Tags.apply(lambda tag: 1 if "Family with young children" in tag else 0)
df["Family_with_older_children"] = df.Tags.apply(lambda tag: 1 if "Family with older children" in tag else 0)
df["With_a_pet"] = df.Tags.apply(lambda tag: 1 if "With a pet" in tag else 0)

In [21]:
df.drop(["Review_Total_Negative_Word_Counts","Review_Total_Positive_Word_Counts","Review_Date","days_since_review"], axis=1, inplace=True)
print("Saving the new csv File")
df.to_csv("Hotel_Reviews_Cleaned.csv",index=False)

Saving the new csv File

**Working on the New Dataset**

In [22]:
import time
import pandas as pd
import numpy as np
import nltk as nltk
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

df=pd.read_csv('/content/Hotel_Reviews_Cleaned.csv')
print("Saving results")
df.to_csv('Hotel_Reviews_NLP.csv',index=False)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

Saving results

In [26]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
df=pd.read_csv('/content/Hotel_Reviews_Cleaned.csv')
start=time.time()
cache=set(stopwords.words("english"))
def remove_stopwords(review):
  text=" ".join([i for i in review.split() if i not in cache])
  return text

df.Negative_Review=df.Negative_Review.apply(remove_stopwords)
df.Positive_Review=df.Positive_Review.apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [27]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
vader_sent=SentimentIntensityAnalyzer()

def cal_sent(review):
  if review=="No Negative" or review=="No Positive":
    return 0
  else:
    return vader_sent.polarity_scores(review)["compound"]

In [30]:
print("Calculating setiments columns for positive and negative reviews")
start=time.time()
df["Negative_Sentiments"]=df.Negative_Review.apply(cal_sent)
df["Positive_Sentiments"]=df.Positive_Review.apply(cal_sent)
end=time.time()
print("Calculating sentiments took "+str(round(end-start,2))+" seconds")

Calculating setiments columns for positive and negative reviews
Calculating sentiments took 156.16 seconds

In [31]:
df=df.sort_values(by=["Negative_Sentiments"],ascending=True)
print(df[["Negative_Review","Negative_Sentiments"]])
df=df.sort_values(by=["Positive_Sentiments"],ascending=True)
print(df[["Positive_Review","Positive_Sentiments"]])

                                          Negative_Review  Negative_Sentiments
186584  So bad experience memories I hotel The first n...              -0.9920
129503  First charged twice room booked booking second...              -0.9896
307286  The staff Had bad experience even booking Janu...              -0.9889
201953  Everything DO NOT STAY AT THIS HOTEL I never i...              -0.9886
452092  No WLAN room Incredibly rude restaurant staff ...              -0.9884
...                                                   ...                  ...
138365  Wifi terribly slow I speed test network upload...               0.9938
79215   I find anything hotel first I walked past hote...               0.9938
278506  The property great location There bakery next ...               0.9945
339189  Guys I like hotel I wish return next year Howe...               0.9948
480509  I travel lot far visited countless number hote...               0.9957

[515738 rows x 2 columns]
                                          Positive_Review  Positive_Sentiments
137893  Bathroom Shower We going stay twice hotel 2 ni...              -0.9820
5839    I completely disappointed mad since reception ...              -0.9780
64158   get everything extra internet parking breakfas...              -0.9751
124178  I didnt like anythig Room small Asked upgrade ...              -0.9721
489137  Very rude manager abusive staff reception Dirt...              -0.9703
...                                                   ...                  ...
417442  We celebrated wedding night Langham I commend ...               0.9985
322920  From moment stepped doors Guesthouse Hotel sta...               0.9985
287419  When first arrived hotel staff incredibly frie...               0.9987
132492  We arrived super cute boutique hotel area expl...               0.9987
179007  We went Andaz 40th birthday celebration This a...               0.9991

[515738 rows x 2 columns]

In [32]:
# Reorder the columns (This is cosmetic, but to make it easier to explore the data later)
df = df.reindex(["Hotel_Name", "Hotel_Address", "Total_Number_of_Reviews", "Average_Score", "Reviewer_Score", "Negative_Sentiment", "Positive_Sentiment", "Reviewer_Nationality", "Leisure_trip", "Couple", "Solo_traveler", "Business_trip", "Group", "Family_with_young_children", "Family_with_older_children", "With_a_pet", "Negative_Review", "Positive_Review"], axis=1)

print("Saving results to Hotel_Reviews_NLP.csv")
df.to_csv(r"Hotel_Reviews_NLP.csv", index = False)

Saving results to Hotel_Reviews_NLP.csv